VERSION --pass-args --arg-scope-and-set 0.7
FROM ghcr.io/nalabelle/build/debian:0.1.0-debian12@sha256:276f85431d63ae77d9284cca4be7c81dc106dc000524a7c1c04982b7f725e630
IMPORT ../info AS info
IMPORT ../manifests AS manifests

ARG --global TARGETARCH
ARG --global __COMPONENT__="commitizen"
ARG --global __VERSION__="0.0.1"
ARG --global REGISTRY="ghcr.io/nalabelle/build"

build-all-platforms:
  BUILD --platform=linux/amd64 --platform=linux/arm64 +build

build:
  BUILD +commitizen

# GITHUB ACTION NOTES
# WORKDIR is set by env variable GITHUB_WORKSPACE
# It will generally be /github/workspace, but don't rely on this
# Don't use USER because github relies on root
commitizen:
  ARG COMMITIZEN_VERSION=3.12.0
  FROM ghcr.io/nalabelle/build/python:0.1.0-python3.11@sha256:cbf0be012881fa8f475911723f4fe17243f587aaded822cc873004ebbff77eba
  ENV PYTHONUNBUFFERED=1
  RUN PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx install \
        commitizen==$COMMITIZEN_VERSION
  RUN git --version && cz version
  RUN git config --system --add safe.directory "*"
  COPY bin/release-cz-bump /usr/local/bin/release-cz-bump
  COPY --if-exists info+git-status/git-dirty /git-dirty
  DO manifests+MANIFEST \
    --VERSION=$__VERSION__ \
    --COMPONENT=$__COMPONENT__
  DO manifests+STANDARD_LABEL
  DO manifests+SAVE_IMAGE --REGISTRY=$REGISTRY
  DO manifests+PRINT

run-cz:
  LOCALLY
  ARG CZ_IMAGE="ghcr.io/nalabelle/build/commitizen/commitizen:0.0.1"
  ARG INPUT_PROJECT_PATH=.
  ARG INPUT_DEBUG="false"
  # match GitHub Action workflow
  LET _path=$(git rev-parse --show-toplevel)
  RUN echo "Working in: ${_path}"
  #WITH DOCKER --load +commitizen
  WITH DOCKER --pull $CZ_IMAGE
    # 100% transferring docker... shows up too late and overwrites output sometimes
    RUN docker run --rm -t \
      --user $(id -u):$(id -g) \
      -e INPUT_PROJECT_PATH \
      -e INPUT_DEBUG \
      -v${_path}:/github/workspace \
      --workdir="/github/workspace" \
      $CZ_IMAGE release-cz-bump
  END
