VERSION --pass-args --arg-scope-and-set 0.7
FROM ghcr.io/nalabelle/build/images/python:0.1.0-python3.12@sha256:1799e3a8ecab5eaf1081a5d044523938711befbf4f71a8407cad6e4d42ece1c5
IMPORT ../manifests AS manifests

ARG --global __COMPONENT__="commitizen"
ARG --global __VERSION__="0.0.1"
ARG --global REGISTRY="ghcr.io/nalabelle/build"

build-all-platforms:
  BUILD --platform=linux/amd64 --platform=linux/arm64 +build

build:
  BUILD +commitizen

# GITHUB ACTION NOTES
# WORKDIR is set by env variable GITHUB_WORKSPACE
# It will generally be /github/workspace, but don't rely on this
# Don't use USER because github relies on root
commitizen:
  ARG COMMITIZEN_VERSION=3.12.0
  FROM ghcr.io/nalabelle/build/images/python:0.1.0-python3.12@sha256:1799e3a8ecab5eaf1081a5d044523938711befbf4f71a8407cad6e4d42ece1c5
  ENV PYTHONUNBUFFERED=1
  RUN PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx install \
        commitizen==$COMMITIZEN_VERSION
  RUN git --version && cz version
  RUN git config --system --add safe.directory "*"
  COPY bin/release-cz-bump /usr/local/bin/release-cz-bump
  DO --pass-args manifests+MANIFEST \
    --VERSION=$__VERSION__ \
    --COMPONENT=$__COMPONENT__
  DO manifests+SAVE_IMAGE --REGISTRY=$REGISTRY
  DO manifests+PRINT

run-cz:
  FROM ghcr.io/nalabelle/build/images/debian:0.1.0@sha256:23e747ec742e2b868338f837c74aaf2cc5332f9d8e678c0316553997837a827c
  LOCALLY
  ARG CZ_IMAGE="ghcr.io/nalabelle/build/commitizen/commitizen:0.0.1"
  ARG INPUT_PROJECT_PATH=.
  ARG INPUT_DEBUG="false"
  # match GitHub Action workflow
  LET _path=$(git rev-parse --show-toplevel)
  RUN echo "Working in: ${_path}"
  #WITH DOCKER --load +commitizen
  WITH DOCKER --pull $CZ_IMAGE
    # 100% transferring docker... shows up too late and overwrites output sometimes
    RUN docker run --rm -t \
      --user $(id -u):$(id -g) \
      -e INPUT_PROJECT_PATH \
      -e INPUT_DEBUG \
      -v${_path}:/github/workspace \
      --workdir="/github/workspace" \
      $CZ_IMAGE release-cz-bump
  END
