VERSION --pass-args --arg-scope-and-set 0.7
FROM ghcr.io/nalabelle/build/debian:0.0.1-debian12

git-status:
  ARG EARTHLY_CI
  LET GIT_STATUS="clean"
  IF [ "$EARTHLY_CI" != "true" ]
    # We should never have a dirty git ref outside of dev
    LOCALLY
    SET GIT_STATUS=$(test -z "$(git status --porcelain)" && echo "clean" || echo "dirty")
  END
  FROM ghcr.io/nalabelle/build/debian:0.0.1-debian12
  IF [ "$GIT_STATUS" = "dirty" ]
    RUN echo "dirty" > /git-dirty
  END
  SAVE ARTIFACT --if-exists /git-dirty
