VERSION --pass-args 0.7
ARG --global TARGETARCH
IMPORT ../ AS b
FROM DOCKERFILE --target debian12-${TARGETARCH} -f digests.Dockerfile .

build-all-platforms:
  BUILD --platform=linux/amd64 --platform=linux/arm64 +build

build:
  BUILD +debian12
  BUILD +helm
  BUILD +python3.11
  BUILD +python3.12

helmfile:
  FROM DOCKERFILE --target helmfile-${TARGETARCH} -f digests.Dockerfile .

CONFIGURE_ENVIRONMENT:
  COMMAND
  ENV LANG="C.UTF-8"
  ENV LC_ALL="C.UTF-8"
  ENV TZ="Etc/UTC"

  RUN groupadd --gid 1999 user
  RUN useradd \
    --uid 1999 \
    --gid 1999 \
    --no-log-init \
    --shell /bin/bash \
    user

CONFIGURE_DEFAULT_PACKAGES:
  COMMAND
  RUN if command -v apt > /dev/null; then \
        apt-get update \
        && DEBIAN_FRONTEND=noninteractive \apt-get install -y --no-install-recommends \
          ca-certificates \
          curl \
          gcc \
          git \
          libc6-dev \
          tzdata \
        && rm -rf /var/lib/apt/lists/*; \
      else \
        echo "The package manager isn't supported"; \
        false; \
      fi

UPSTREAM:
  COMMAND
  ARG --required version
  ARG EARTHLY_TARGET_NAME
  FROM DOCKERFILE --target ${EARTHLY_TARGET_NAME}${version}-${TARGETARCH} -f digests.Dockerfile .

debian12:
  FROM +debian --version=12
  DO --pass-args b+SAVE_IMAGE --target=debian --version=12.2

debian:
  DO --pass-args +UPSTREAM
  DO +CONFIGURE_ENVIRONMENT
  DO +CONFIGURE_DEFAULT_PACKAGES

python3.12:
  FROM +python --version=3.12
  DO --pass-args b+SAVE_IMAGE --target=python --version=3.12

python3.11:
  FROM +python --version=3.11
  DO --pass-args b+SAVE_IMAGE --target=python --version=3.11

python:
  DO --pass-args +UPSTREAM
  DO +CONFIGURE_ENVIRONMENT
  DO +CONFIGURE_DEFAULT_PACKAGES
  # renovate: datasource=github-releases depName=pypa/pipx
  ARG PIPX_VERSION=1.2.1
  RUN curl -fssLO https://github.com/pypa/pipx/releases/download/1.2.1/pipx.pyz \
        && mv pipx.pyz /usr/local/bin/pipx \
        && chmod +x /usr/local/bin/pipx \
        && pipx --version
  DO +POETRY

POETRY:
  COMMAND
  ENV PYTHONIOENCODING="UTF-8"

  # renovate: datasource=github-releases depName=python-poetry/poetry
  ARG POETRY_VERSION=1.6.1
  ENV POETRY_HOME=/opt/poetry
  ENV POETRY_VENV=/opt/poetry-venv
  ENV POETRY_CACHE_DIR=/opt/.cache

  RUN PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx \
      install poetry=="${POETRY_VERSION}"

  ENV PATH="${PATH}:${POETRY_VENV}/bin"

helm:
  FROM --pass-args +debian12
  # renovate: datasource=github-releases depName=helm/helm
  ARG HELM_VERSION=3.13.1
  COPY (+helm-build/helm --VERSION=${HELM_VERSION}) /usr/local/bin/helm
  USER user
  DO --pass-args b+SAVE_IMAGE --version=${HELM_VERSION}

helm-build:
  ARG --required VERSION
  ARG _download="helm-v${VERSION}-linux-${TARGETARCH}.tar.gz"

  FROM --pass-args +debian12
  WORKDIR /build
  COPY checksums/${_download}.sha256sum .
  RUN curl -fsSLO https://get.helm.sh/${_download}
  RUN sha256sum --check --status < ${_download}.sha256sum
  RUN tar -zxvf ${_download} \
    && mv linux-${TARGETARCH}/helm helm \
    && rm -r linux-${TARGETARCH}
  SAVE ARTIFACT helm /helm
