VERSION --pass-args --arg-scope-and-set 0.7
ARG --global TARGETARCH
#IMPORT github.com/nalabelle/build AS b
IMPORT ../ AS b
FROM ghcr.io/nalabelle/build/debian12@sha256:72d9a3e195826990664c024ee1e54758fbc3484bfc57ae6d920464b81efebb23

build-all-platforms:
  BUILD --platform=linux/amd64 --platform=linux/arm64 +build

build:
  BUILD +helm
  BUILD +helmfile

helmfile:
  FROM DOCKERFILE --target helmfile-${TARGETARCH} -f digests.Dockerfile .

helm:
  # renovate: datasource=github-releases depName=helm/helm
  ARG HELM_VERSION=3.13.1
  COPY (+helm-build/helm --VERSION=${HELM_VERSION}) /usr/local/bin/helm
  USER user
  DO --pass-args b+SAVE_IMAGE --version=${HELM_VERSION}

helm-build:
  ARG --required VERSION
  ARG _download="helm-v${VERSION}-linux-${TARGETARCH}.tar.gz"

  WORKDIR /build
  COPY checksums/${_download}.sha256sum .
  RUN curl -fsSLO https://get.helm.sh/${_download}
  RUN sha256sum --check --status < ${_download}.sha256sum
  RUN tar -zxvf ${_download} \
    && mv linux-${TARGETARCH}/helm helm \
    && rm -r linux-${TARGETARCH}
  SAVE ARTIFACT helm /helm
