name: "CI: images"

on:
  workflow_dispatch: {}
  schedule:
    - cron: '16 0 * * 1'
  push:
    branches: [ main ]
    paths:
      - 'images/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'images/**'

concurrency:
  group: ${{ github.head_ref || github.ref  }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: nalabelle/build/.github/workflows/ci.yaml@main
    with:
      workdir: 'images'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
