name: "CI"

on:
  workflow_call:
    inputs:
      earthly_version:
        default: 'latest'
        required: false
        type: string
      workdir:
        required: false
        type: string
      target:
        default: '+build-all-platforms'
        required: false
        type: string
      cache:
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      FORCE_COLOR: 1
    steps:
      - name: Set up QEMU for multi-platform builds
        id: qemu
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: earthly/actions-setup@v1
        with:
          version: ${{ inputs.earthly_version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        # Only push if this was a merge to main
        run: |
          [ -n "${{ inputs.workdir }}" ] && pushd "${{ inputs.workdir }}"
          earthly \
            --ci \
            ${{ inputs.cache && format('--remote-cache={0}', inputs.cache) || '' }} \
            ${{ (github.event_name == 'push' && github.ref_name == 'main') && '--push' || '' }} \
            "${{ inputs.target }}"
