name: "Bump version: text-tools"

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'text-tools/**'

jobs:
  bump-version:
    uses: nalabelle/build/.github/workflows/bumpversion.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      workdir: 'text-tools'
