name: "Versioning"

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.21
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Create bump and changelog
        run: |
          pushd commitizen >/dev/null
          earthly +run-cz \
              --INPUT_PROJECT_PATH="${{ inputs.workdir }}"
          popd >/dev/null
          echo "STATUS:"
          git status
          echo "CHANGELOG:"
          cat ${{ inputs.workdir }}/body.md 2>/dev/null || true
          echo "VERSION:"
          cat ${{ inputs.workdir }}/version.txt 2>/dev/null || true
          #      - name: Release
          #        uses: softprops/action-gh-release@v1
          #        with:
          #          body_path: "${{ inputs.workdir }}/body.md"
          #          tag_name: "${{ env.REVISION }}"
          #        env:
          #          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
