name: "Versioning"

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.21
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - name: Create bump and changelog
        run: |
          cd commitizen
          earthly +run-cz \
              --INPUT_PROJECT_PATH="${{ inputs.workdir}}" \
              --INPUT_DEBUG="true"
            #- name: Release
            #  uses: softprops/action-gh-release@v1
            #  with:
            #    body_path: "body.md"
            #    tag_name: "${{ env.REVISION }}"
            #  env:
            #    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
